  services:
    api:
      build: .
      container_name: api
      ports:
        - "3000:3000"
      env_file:
        - .env
      depends_on:
        - mongo
        - redis
      volumes:
        - .:/app
      networks:
        - app-network

    mongo:
      image: mongo
      container_name: mongo
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
      networks:
        - app-network

    redis:
      image: redis
      container_name: redis
      command: redis-server --port 6380
      ports:
        - "6380:6380"
      volumes:
        - redis_data:/data
      networks:
        - app-network

  networks:
    app-network:
      driver: bridge

  volumes:
    mongo_data:
    redis_data:
